import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import { saveAs } from "file-saver";
import { Inter } from '@next/font/google'


// const inter = Inter({ subsets: ['latin'] })


export default function Home() {


    const [fullname, setFullname] = useState("");
    const [email, setEmail] = useState("");
    const [Phone, setPhone] = useState("");
    const [message, setMessage] = useState("");
  
    //   Form validation
    const [errors, setErrors] = useState({});
  
    //   Setting button text
    const [buttonText, setButtonText] = useState("Send");
  
    const [showSuccessMessage, setShowSuccessMessage] = useState(false);
    const [showFailureMessage, setShowFailureMessage] = useState(false);


    const saveFile = () => {
        saveAs(
          "https://res.cloudinary.com/miamiwrapz-com/image/upload/v1646400566/kevral_resume_w0kmcw.ai",
          "KevralFrancisCV.pdf"
        );
      };


  
    const handleValidation = () => {
      let tempErrors = {};
      let isValid = true;
  
      if (fullname.length <= 0) {
        tempErrors["fullname"] = true;
        isValid = false;
      }
      if (email.length <= 0) {
        tempErrors["email"] = true;
        isValid = false;
      }
      if (Phone.length <= 0) {
        tempErrors["Phone"] = true;
        isValid = false;
      }
      if (message.length <= 0) {
        tempErrors["message"] = true;
        isValid = false;
      }
  
      setErrors({ ...tempErrors });
      console.log("errors", errors);
      return isValid;
    };
  
    //   const [form, setForm] = useState(false);
  
    const handleSubmit = async (e) => {
      e.preventDefault();
  
      let isValidForm = handleValidation();
  
      if (isValidForm) {
        setButtonText("Sending");
        const res = await fetch("/api/sendgrid", {
          body: JSON.stringify({
            email: email,
            fullname: fullname,
            Phone: Phone,
            message: message,
          }),
          headers: {
            "Content-Type": "application/json",
          },
          method: "POST",
        });
  
        const { error } = await res.json();
        if (error) {
          console.log(error);
          setShowSuccessMessage(false);
          setShowFailureMessage(true);
          setButtonText("Send");
  
          // Reset form fields
          setFullname("");
          setEmail("");
          setMessage("");
          setPhone("");
          return;
        }
        setShowSuccessMessage(true);
        setShowFailureMessage(false);
        setButtonText("Send");
        // Reset form fields
        setFullname("");
        setEmail("");
        setMessage("");
        setPhone("");
      }
      console.log(fullname, email, Phone, message);
    };





  return (
    <>


<Head>
<title>Create Next App</title>
<meta name="description" content="Generated by create next app" />
<link rel="icon" href="/favicon.ico" />

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossOrigin="true" />
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"></link>



</Head>

    <header>
        <nav>

            <a href="#">

                <div className="kev_nav_item">
                    <i className="fa fa-home fa-2x" aria-hidden="true"></i>
                </div>

            </a>

            <a href="#ABOUT-ME">

                <div className="kev_nav_item">
                    <i className="fa fa-user-circle fa-2x" aria-hidden="true"></i>
                </div>

            </a>

            <a href="#EDUCTAION-EXP">

                <div className="kev_nav_item">
                    <i className="fa fa-graduation-cap fa-2x" aria-hidden="true"></i>
                </div>

            </a>

            <a href="#EDUCTAION-EXP">

                <div className="kev_nav_item">
                    <i className="fa fa-briefcase fa-2x" aria-hidden="true"></i>
                </div>

            </a>


            <a href="#SKILLS">

                <div className="kev_nav_item">
                    <i className="fa fa-code fa-2x" aria-hidden="true"></i>
                </div>

            </a>

            <a href="#PORTFOLIO">

                <div className="kev_nav_item">
                    <i className="fa-solid fa-code-fork fa-2x" aria-hidden="true"></i>
                </div>
               
            </a>

            <a href="#TOOLS">

            <div className="kev_nav_item">
                <i className="fa-sharp fa-solid fa-screwdriver-wrench fa-2x" aria-hidden="true"></i>
            </div>

            </a>

            <a href="#CONTACT-ME">

            <div className="kev_nav_item">
                <i className="fa fa-phone-square fa-2x" aria-hidden="true"></i>
            </div>

            </a>


        </nav>




    </header>



    <div className="nav" role="navigation">
        <div id="menuToggle">
            <input type="checkbox" />
            <span></span>
            <span></span>
            <span></span>
            <ul id="menu">
                <li><a href="#">Home</a></li>
                <li><a href="#ABOUT-ME">About</a></li>
                <li><a href="#EDUCTAION-EXP">Education</a></li>
                <li><a href="#EDUCTAION-EXP">Work Experience</a></li>
                <li><a href="#SKILLS">Contact Me</a></li>
                <li><a href="#PORTFOLIO">Contact Me</a></li>
                <li><a href="#TOOLS">Tools</a></li>
                <li><a href="#CONTACT-ME">Contact Me</a></li>
            </ul>
        </div>
    </div>


    <main>

        <div className="kev_section">
            <div className="kev_container  kev_row">
                <div className="hero-image-section">
                    {/* <img src="kevralfrancisportfolioimage.c9398925.jpg" /> */}
                    <Image

                    src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360240/kevralfrancisportfolioimage.c9398925_uatyyx.jpg"
                    
                    alt="Picture of the author"
                    width={500}
                    height={500}

                    />

                </div>

                <div className="mobile-hero-image-section">
                    {/* <img src="profile-image.png" /> */}

                    <Image

                    src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360242/profile-image_sbjyvn.png"
                    alt="Picture of the author"
                    width={500}
                    height={500}

                    />

                </div>
                <div className="hero-info-section">
                    <h2> I am Kevral Francis <span className="text-gradient">Software Engineer</span></h2>
                    <p>I am a US-based Software Engineer for both frontend and backend development, focused on crafting
                        clean and user‑friendly experiences. I am passionate about building excellent software that
                        improves the lives of those around me.</p>
                    <button onClick={saveFile} type="button" className="btn btn-primary btn-lg button_gradient">Download CSV</button>
                    <a href="#ABOUT-ME">  <button type="button" className="btn btn-secondary btn-lg">About Me</button> </a>
                </div>
            </div>
        </div>

        <div id="ABOUT-ME" className="kev_section dark_grey_background">
            <div className="kev_container">
                <div className="kev-Section-title">
                    <h1>About Me</h1>
                </div>
                <div className="aboutme-twocol">
                    <div className="aboutme-info">
                        {/* <img src="profile-image.jpg" /> */}
                        <Image

                            src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360242/profile-image_sbjyvn.png"

                            alt="Picture of the author"
                            width={500}
                            height={500}

                            />
                        <div>
                            <p>
                                Name : Kevral Francis
                            </p>
                            <p>
                                Age : 29
                            </p>
                            <p>
                                Nationality: US Citizen
                            </p>
                            <p>
                                Freelance : Available
                            </p>
                            <p>
                                Address : Miami Florida
                            </p>
                            <p>
                                Phone : +1(786)426-4353
                            </p>
                            <p>
                                Email : kevralfrancis29@gmail.com
                            </p>
                        </div>
                    </div>
                    <div className="aboutme-bio">

                        <p>

                            I have worked as a software engineer for over 6+ years. I spend the first few years of my
                            career being a web designer/graphic designer working with HTML, CSS, and javascript. I have
                            grown to become a full-stack developer, Working on projects with frameworks and libraries
                            such as React, Angular, and Vue for front-end development. I also use Express JS in the
                            backend creating Rest API, WebSockets API, and GraphQL queries and mutations in Node Js,
                            Generating Spring Boot Applications for Java Backend Development, and composing Laravel PHP
                            applications for backend development. However, throughout my process, I&apos;ve developed a core
                            concept. A concept that allows me to see through the languages and the frameworks.
                        </p>
                        <p>
                            I have developed the knowledge of rest API, Websocket API and the full context of how they
                            work, Quering and Mutations with graphQL, MVC framework architectural pattern, creating
                            routes, controllers, database connection, data modeling, and middlewares. Front-end
                            development, using Vanilla Javascript, Javascript libraries and frameworks, Shopify Liquid,
                            and PHP to perform tasks such as adding directives, conditional rendering, list rendering,
                            state management for both globally and at the component level, and data fetching from both
                            custom servers connection and external API.
                        </p>
                        <p>
                            I have also taken the opportunity to learn cloud Architecture, such as AWS and GCP.
                            Understanding software deployment allows me to design, deploy, configure and maintain
                            applications with high-level System Design that provide high availability and scalability.
                            These core concepts I developed as a Software Engineer made it super easy to adapt to a new
                            framework, languages, and systems, navigate through documentation, and find reputable
                            sources to complete a project in a predicted timeline. Throughout University, I have learned
                            to understand the core concept of problem-solving, algorithms, and data structure,
                            calculating time complexity and space complexity to produce more effective, efficient, and
                            optimized codes. My passion, dedication, and discipline for software and system engineering
                            motivate me to acquire this knowledge. The same drive, passion, dedication, and discipline I
                            tried to impart to the right team and organization.
                        </p>

                        <button onClick={saveFile} type="button" className="btn btn-primary btn-lg button_gradient">Download CSV </button>

                    </div>

                </div>
            </div>
        </div>
        <div id="EDUCTAION-EXP" className="kev_section_col">
            <div className="kev_container">
                <div className="kev-Section-title_left ">
                    <h1 className="text-gradient ">Education</h1>
                </div>
                <div className="education-two-col">
                    <div className="first-education">
                        <h2>Barry University</h2>
                        <p> Bachelor of Science, Information Technology with Specialization Software Engineering
                        </p>

                        <p>Jan 2018 - Jun 2022</p>
                        <p> Grade: 3.300
                        </p>
                    </div>
                    <div className="first-education">

                        <h2>Udemy & Skillshare</h2>
                        <p> Software Engineering continuing education, which helps me to keep up to date with the latest technology and systems that have been put in place to make software engineering more effective.
                            
                        </p>

                        <p>Jan 2016 - CURRENT</p>
                        <p> Completion: 9 Course
                        </p>

                    </div>
                </div>




                <div className="kev-Section-title_left">
                    <h1 className="text-gradient ">Work Experiences</h1>
                </div>
                <div className="education-two-col">
                    <div className="first-education">
                        <h2>Web Developer</h2>
                        <p> Perry Ellis International · Full-time Perry Ellis International · Full-time
                        </p>

                        <p>Jul 2022 - Present · 6 mos Jul 2022 - Present · 6 mos</p>
                        <p> Miami-Fort Lauderdale Area Miami-Fort Lauderdale Area
                        </p>
                        <p>Web Developer is responsible for approaching website development from a solutions
                            perspective: considering the end user experience as well as from the back-end usability and
                            flexibility. Collaborate with creative and technical teams to bring to life innovative
                            sites. Great communication, attention to detail, and desire to grow and learn new
                            disciplines.
                        </p>
                    </div>
                    <div className="first-education">

                        <h2>Senior Web Developer / Senior Graphic Designer</h2>
                        <p> Kingdom Marketing Group · Full-time Kingdom Marketing Group · Full-time
                        </p>

                        <p>Sep 2015 - Jul 2022 · 6 yrs 11 mosSep 2015 - Jul 2022 · 6 yrs 11 mos
                        </p>
                        <p> Miami-Fort Lauderdale Area Miami-Fort Lauderdale Area
                        </p>
                        <p>Kingdom Marketing Group is an organization that manage many different companies in the
                            South Florida Area. Some of there Major companies are; Miami Wrapz, Frame The Stars,
                            Website Design & Marketing Agency, Miami T-shirt Printers, etc. As a Senior Web
                            developer and Senior Graphic designer I manage a small team of Six to that provide
                            design, development and marketing services for all sub companies and also clients for
                            these companies mention above.Kingdom Marketing Group is an organization that manage
                            many different companies in the South Florida Area.</p>

                    </div>
                </div>
        
            </div>




        </div>
        <div id="SKILLS" className="kev_section dark_grey_background">
            <div className="kev_container">
                <div className="kev-Section-title">
                    <h1> Core Skill Areas
                    </h1>
                </div>

                <div className="skill-three-col">
                    <div className="skill">
                        <div className="skill-icon">
                            <i className="fa fa-paint-brush fa-3x" aria-hidden="true"></i>

                        </div>
                        <div className="skill-subtitle">Graphic/UX Design</div>
                        <div className="skill-paragraph">My first experience in web development was as a UX designer. From
                            creating web to mobile UI components for developers to convert into re-usable code using
                            tools such as Adobe Photoshop, Adobe Illustrator, Sketch, and Adobe XD. To this day,
                            building the front end of projects, I find myself executing a project faster by designing
                            first with a designing tool, then converting it to code. As a Software Engineer, working on
                            projects as a freelancer or on the job, timing is critical.</div>
                    </div>
                    <div className="skill">
                        <div className="skill-icon">
                            <i className="fa fa-laptop fa-3x" aria-hidden="true"></i>
                        </div>
                        <div className="skill-subtitle">Frontend Development</div>
                        <div className="skill-paragraph">Experience from basic HTML, CSS, and JavaScript to Advance
                            JavaScript Frameworks and Libraries such as React JS, Vue JS, and Angular JS. I fully
                            understanding how to work with promises and state management, both globally and at a
                            component level. Design clean reusable and flexible components that use properties to update
                            other components in the component tree, routing, conditional rendering, and list redendering
                            of data for users interactions.</div>
                    </div>

                    <div className="skill">
                        <div className="skill-icon">
                            <i className="fa fa-code fa-3x" aria-hidden="true"></i>
                        </div>
                        <div className="skill-subtitle">Backend Development</div>
                        <div className="skill-paragraph">As A backend developer, I poses a strong understanding of working
                            with Rest API to perform the CRUD operation, working with middlewares for additional
                            functionality, and using GraphQL querying and mutations in Express JS to pass data to the
                            frontend. Creating database model schemas with Mongoose for MongoDB and making SQL database
                            connections.</div>
                    </div>

                    <div className="skill">
                        <div className="skill-icon">
                            <i className="fa fa-database fa-3x" aria-hidden="true"></i>
                        </div>
                        <div className="skill-subtitle">Database Andminstration</div>
                        <div className="skill-paragraph">I have a strong understanding of working both with SQL and NoSQL
                            databases. SQL Database I work with so far are MSSQL, MySQL, and PostgreSQL and the NoSQL I
                            work with so far is MongoDB. From workinging with cloud service to installing database
                            workbench and playground to Create, Read, Update, Delete and Drop data from the database.
                        </div>
                    </div>

                    <div className="skill">
                        <div className="skill-icon">
                            <i className="fa fa-server fa-3x" aria-hidden="true"></i>
                        </div>
                        <div className="skill-subtitle">System Design</div>
                        <div className="skill-paragraph">As part of my journey as a software engineer, I ran into many struggles when deploying code to a test environment on a single server or to the production environment in the cloud with multiple virtual machines and load balancing of traffic. With this part of my journey, I learn how to design highly available and scalable systems. Transferring code from On-premise systems to cloud services, configuring VPC, load balancing application traffic, and setting up Kubernetes or serverless functions that speed up deployment. I also understand the different types of database storage and communication methods between servers and databases.</div>
                    </div>

                    <div className="skill">
                        <div className="skill-icon">
                            <i className="fa fa-paper-plane fa-3x" aria-hidden="true"></i>
                        </div>
                        <div className="skill-subtitle">Deployment</div>
                        <div className="skill-paragraph">As a software engineer, I clearly understand the importance of
                            uniting testing, integration testing, and most of all, successful deployment. I took time
                            out to study AWS Cloud services such as EC2 instances (Virtual Servers), S3 scalable storage
                            in the cloud, database connection with RDS for SQL database and DynamoDB for NoSQL database,
                            elastic load balancing, networking, security, analytics and more. I am aslo capable of
                            designing, developing, and deploying a software on other platfrom such as DigitalOcean,
                            Vercel, heroku, and different type CPanel hosting service run with WHMCS. Despite all the
                            services listed above, I am capable of learning about a new platform fast enough to meet
                            most project goals.</div>
                    </div>
                </div>

            </div>


        </div>






        <div id="PORTFOLIO" className="kev_section">
            <div className="kev_container">
                <div className="kev-Section-title">
                    <h1> Portfolio Projects
                    </h1>
                </div>

                <div className="skill-three-col">
                    <div className="skill floating">

                        {/* <img src="Project1.png" /> */}

                        <Image

src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360241/Project1_k3ikln.png"

alt="Picture of the author"
width={500}
height={500}

/>
                        
                        <div className="skill-paragraph">Miami Wrapz</div>
                    </div>
                    <div className="skill floating">

                        {/* <img src="Project3.png" /> */}
                        <Image

src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360242/Project3_toxcwq.png"

alt="Picture of the author"
width={500}
height={500}

/>
                        <div className="skill-paragraph">Promo Graphics and Printing</div>
                    </div>

                    <div className="skill floating">

                        {/* <img src="Project4.png" /> */}
                        <Image

src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360243/Project4_ljxxpk.png"

alt="Picture of the author"
width={500}
height={500}

/>
                        <div className="skill-paragraph">Blue Horizon Windows and Doors</div>
                    </div>

                    <div className="skill floating">

                        {/* <img src="Project5.png" /> */}

                        <Image

src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360243/Project5_tyhgrj.png"

alt="Picture of the author"
width={500}
height={500}

/>
                        <div className="skill-paragraph">Uptop Jamaican Restaurant and lounge</div>
                    </div>

                    <div className="skill floating">

                        {/* <img src="Project6.png" /> */}

                        <Image

src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360243/Project6_kdoyyh.png"

alt="Picture of the author"
width={500}
height={500}

/>
                        <div className="skill-paragraph"> Branded Bunch</div>
                    </div>

                    <div className="skill floating">

                        {/* <img src="Project1.png" /> */}

                        <Image

src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360242/Project2_inbzkl.png"

alt="Picture of the author"
width={500}
height={500}

/>
                        <div className="skill-paragraph">Frame The Stars</div>
                    </div>
                </div>

            </div>


        </div>



        <div id="TOOLS" className="kev_section dark_grey_background">
            


        <div className="kev_container">
                <div className="kev-Section-title tool-title">
                    <h1> Development Tools
                    </h1>
                </div>

                <div className="tool-subtitle ">
                    <h1> Frontend Development Tools
                    </h1>
                </div>

                <div className="tool-three-col">
                    <div className="tool floating">

                    <Image className="HTML" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360244/Tool30_cdtxf3.png" alt="Picture of the author"
width={500}
height={500}
/>

                        <div className="tool-paragraph">HTML</div>
                    </div>
                    <div className="tool floating">

                        <Image className="CSS" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360243/Tool29_qjdbf5.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">CSS</div>
                    </div>

                    <div className="tool floating">

                        <Image className="Javascript" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360243/Tool28_iddva6.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">Javascript</div>
                    </div>

                    <div className="tool floating">

                        <Image className="React" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360243/Tool27_oxwbfr.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">React</div>
                    </div>

                    <div className="tool floating">

                        <Image className="Angular" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360243/Tool26_r9uols.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">Angular</div>
                    </div>

                    <div className="tool floating">

                        <Image className="Vue" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360243/Tool25_eanewe.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">Vue</div>
                    </div>
                </div>



                <div className="tool-subtitle">
                    <h1> Backend Development Tools
                    </h1>
                </div>

                <div className="tool-three-col">

                    <div className="tool floating">

                        <Image className="Node-JS" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360243/Tool24_qw3pnm.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">Node JS</div>
                    </div>

                    <div className="tool floating">

                        <Image className="Spring-Boot" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360242/Tool23_a1zmz3.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">Spring-Boot</div>
                    </div>

                    <div className="tool floating">

                        <Image className="ASP-NET" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360242/Tool22_rkdl63.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">ASP.NET</div>
                    </div>

                    <div className="tool floating">

                        <Image className="Laravel" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360242/Tool21_njjzzx.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">Laravel</div>
                    </div>
              
                </div>






                <div className="tool-subtitle">
                    <h1> Database Tools
                    </h1>
                </div>

                <div className="tool-three-col">
                    <div className="tool floating">

                        <Image className="MySQL" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360242/Tool19_lwyfgc.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">MySQL</div>
                    </div>
                    <div className="tool floating">

                        <Image className="MSSQL" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360241/Tool18_ohyf8x.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">MSSQL</div>
                    </div>
                    <div className="tool floating">

                        <Image className="Oracle" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360241/Tool17_v5pprl.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">Oracle</div>
                    </div>
                    <div className="tool floating">

                        <Image className="GraphQL" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360240/Tool16_jqz63q.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">GraphQL</div>
                    </div>
                    <div className="tool floating">

                        <Image className="PostgresSQL" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360240/Tool15_bxxhom.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">PostgresSQL</div>
                    </div>

                    <div className="tool floating">

                        <Image className="Redis" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360240/Tool14_ekih0q.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">Redis</div>
                    </div>

                    <div className="tool floating">

                        <Image className="MongoDB" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360244/Tool3_q7dgic.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">MongoDB</div>
                    </div>

                    <div className="tool floating">

                        <Image className="Cassandra" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360244/Tool2_xnaojm.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">Cassandra</div>
                    </div>

                    <div className="tool floating">

                        <Image className="Hadoop" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360244/Tool1_ved2tg.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">Hadoop</div>
                    </div>
                </div>





                <div className="tool-subtitle">
                    <h1> Deployment Tools
                    </h1>
                </div>

                <div className="tool-three-col">
                    <div className="tool floating">

                        <Image className="Git" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360240/Tool13_vctbtw.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">Git</div>
                    </div>
                    <div className="tool floating">

                        <Image className="GitHub" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360240/Tool12_ebxwsc.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">GitHub</div>
                    </div>
                    <div className="tool floating">

                        <Image className="Docker" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360240/Tool11_yianxd.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">Docker</div>
                    </div>
                    <div className="tool floating">

                        <Image className="Padmon" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360245/Tool10_rnetrp.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">Padmon</div>
                    </div>
                    <div className="tool floating">

                        <Image className="Kubernetes" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360245/Tool9_i40gh4.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">Kubernetes</div>
                    </div>

                    <div className="tool floating">

                        <Image className="Jenkins" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360244/Tool8_gmr4j1.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">Jenkins</div>
                    </div>

                    <div className="tool floating">

                        <Image className="Linux" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360244/Tool7_hywhtf.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">Linux</div>
                    </div>

                    <div className="tool floating">

                        <Image className="AWS" src="https://res.cloudinary.com/dn291drsi/image/upload/v1672360244/Tool6_eu2dla.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">AWS</div>
                    </div>

                    <div className="tool floating">

                        <Image className="GCP" src="https://res.cloudinary.com/dn291drsi/image/upload/v1673801746/Tool31_rqyosf.png" alt="Picture of the author"
width={500}
height={500}
/>
                        <div className="tool-paragraph">GCP</div>
                    </div>
                </div>
















            </div>






        </div>















        <div id="CONTACT-ME" className="kev_section">
            <div className="kev_container">
                <div className="kev-Section-title tool-title">
                    <h1> You Can hire Me To:
                    </h1>
                </div>





                <p className="home-text02"> Work at any of these levels of a software engineering project</p>


                <div className="home-container01">
                    <div className="home-step">
                        <div className="home-container02">
                            <div className="home-line"></div>
                            <div className="home-container03">
                                <svg viewBox="0 0 1024 1024" className="home-icon">
                                    <path
                                        d="M634 558q92-64 92-174 0-88-63-151t-151-63-151 63-63 151q0 46 27 96t65 78l36 26v98h172v-98zM512 86q124 0 211 87t87 211q0 156-128 244v98q0 18-12 30t-30 12h-256q-18 0-30-12t-12-30v-98q-128-88-128-244 0-124 87-211t211-87zM384 896v-42h256v42q0 18-12 30t-30 12h-172q-18 0-30-12t-12-30z">
                                    </path>
                                </svg>
                            </div>
                            <div className="home-line1"></div>
                        </div>
                        <div className="home-container04">
                            <h1 className="home-text05"><span>Ideate</span></h1>
                            <span className="home-text07">
                                <span>
                                    Work with teams and decision makers in organizations to plan
                                    the best solutions. for problems, automation or tools that
                                    need to be developed.&nbsp;
                                </span>
                                <br />
                            </span>
                        </div>
                    </div>
                    <div className="home-step1">
                        <div className="home-container05">
                            <div className="home-line2"></div>
                            <div className="home-container06">
                                <svg viewBox="0 0 1024 1024" className="home-icon2">
                                    <path
                                        d="M746 512q26 0 45-18t19-46-19-46-45-18-45 18-19 46 19 46 45 18zM618 342q26 0 45-19t19-45-19-45-45-19-45 19-19 45 19 45 45 19zM406 342q26 0 45-19t19-45-19-45-45-19-45 19-19 45 19 45 45 19zM278 512q26 0 45-18t19-46-19-46-45-18-45 18-19 46 19 46 45 18zM512 128q158 0 271 100t113 242q0 88-63 150t-151 62h-74q-28 0-46 19t-18 45q0 22 16 42t16 44q0 28-18 46t-46 18q-160 0-272-112t-112-272 112-272 272-112z">
                                    </path>
                                </svg>
                            </div>
                            <div className="home-line3"></div>
                        </div>
                        <div className="home-container07">
                            <h1 className="home-text10"><span>Design</span></h1>
                            <span className="home-text12">
                                <span>
                                    Will be able to assist with UX/UI Designs and System Designs
                                    form a Low level or High Level perspective
                                </span>
                                <br />
                            </span>
                        </div>
                    </div>
                    <div className="home-step2">
                        <div className="home-container08">
                            <div className="home-line4"></div>
                            <div className="home-container09">
                                <svg viewBox="0 0 1024 1024" className="home-icon4">
                                    <path d="M576 736l96 96 320-320-320-320-96 96 224 224z"></path>
                                    <path d="M448 288l-96-96-320 320 320 320 96-96-224-224z"></path>
                                </svg>
                            </div>
                            <div className="home-line5"></div>
                        </div>
                        <div className="home-container10">
                            <h1 className="home-text15"><span>Develop</span></h1>
                            <span className="home-text17">
                                <span>
                                    Will be able to developed full stack application from front
                                    end to backend with tools and packages need to make the
                                    project securely successful
                                </span>
                                <br />
                            </span>
                        </div>
                    </div>
                    <div className="home-step3">
                        <div className="home-container11">
                            <div className="home-line6"></div>
                            <div className="home-container12">
                                <svg viewBox="0 0 1024 1024" className="home-icon7">
                                    <path
                                        d="M480 64c-265.096 0-480 214.904-480 480 0 265.098 214.904 480 480 480 265.098 0 480-214.902 480-480 0-265.096-214.902-480-480-480zM751.59 704c8.58-40.454 13.996-83.392 15.758-128h127.446c-3.336 44.196-13.624 87.114-30.68 128h-112.524zM208.41 384c-8.58 40.454-13.996 83.392-15.758 128h-127.444c3.336-44.194 13.622-87.114 30.678-128h112.524zM686.036 384c9.614 40.962 15.398 83.854 17.28 128h-191.316v-128h174.036zM512 320v-187.338c14.59 4.246 29.044 11.37 43.228 21.37 26.582 18.74 52.012 47.608 73.54 83.486 14.882 24.802 27.752 52.416 38.496 82.484h-155.264zM331.232 237.516c21.528-35.878 46.956-64.748 73.54-83.486 14.182-10 28.638-17.124 43.228-21.37v187.34h-155.264c10.746-30.066 23.616-57.68 38.496-82.484zM448 384v128h-191.314c1.88-44.146 7.666-87.038 17.278-128h174.036zM95.888 704c-17.056-40.886-27.342-83.804-30.678-128h127.444c1.762 44.608 7.178 87.546 15.758 128h-112.524zM256.686 576h191.314v128h-174.036c-9.612-40.96-15.398-83.854-17.278-128zM448 768v187.34c-14.588-4.246-29.044-11.372-43.228-21.37-26.584-18.74-52.014-47.61-73.54-83.486-14.882-24.804-27.75-52.418-38.498-82.484h155.266zM628.768 850.484c-21.528 35.876-46.958 64.746-73.54 83.486-14.184 9.998-28.638 17.124-43.228 21.37v-187.34h155.266c-10.746 30.066-23.616 57.68-38.498 82.484zM512 704v-128h191.314c-1.88 44.146-7.666 87.040-17.28 128h-174.034zM767.348 512c-1.762-44.608-7.178-87.546-15.758-128h112.524c17.056 40.886 27.344 83.806 30.68 128h-127.446zM830.658 320h-95.9c-18.638-58.762-44.376-110.294-75.316-151.428 42.536 20.34 81.058 47.616 114.714 81.272 21.48 21.478 40.362 44.938 56.502 70.156zM185.844 249.844c33.658-33.658 72.18-60.932 114.714-81.272-30.942 41.134-56.676 92.666-75.316 151.428h-95.898c16.138-25.218 35.022-48.678 56.5-70.156zM129.344 768h95.898c18.64 58.762 44.376 110.294 75.318 151.43-42.536-20.34-81.058-47.616-114.714-81.274-21.48-21.478-40.364-44.938-56.502-70.156zM774.156 838.156c-33.656 33.658-72.18 60.934-114.714 81.274 30.942-41.134 56.678-92.668 75.316-151.43h95.9c-16.14 25.218-35.022 48.678-56.502 70.156z">
                                    </path>
                                </svg>
                            </div>
                            <div className="home-line7"></div>
                        </div>
                        <div className="home-container13">
                            <h1 className="home-text20"><span>Deploy</span></h1>
                            <span className="home-text22">
                                <span>
                                    I will be able to deploy application in the cloud or
                                    on-premises servers with high availabilty and scalability
                                    configuration
                                </span>
                                <br />
                            </span>
                        </div>
                    </div>
                </div>
            
         







                <div className="contact-area">

                    {/* <form onSubmit={handleSubmit} >
                            <input type="text" placeholder="Company Name" 
                            value={fullname}
                            onChange={(e) => {
                            setFullname(e.target.value);
                            }}
                            name="fullname"
                            />

                        <input type="email" placeholder="Email" 
                           value={email}
                           onChange={(e) => {
                           setEmail(e.target.value);
                            }}
                           name="fullname"
                           />
                        
                        <input type="tel" placeholder="Phone Number" 
                            value={phone}
                            onChange={(e) => {
                            setPhone(e.target.value);
                            }}
                            name="fullname"
                            />
                        
                        <textarea 
                            placeholder="Any Additional Information..."
                            name="message"
                            value={message}
                            onChange={(e) => {
                            setMessage(e.target.value);
                            }}
                            
                            ></textarea>


<button
              type="submit"
              className="px-10 mt-8 py-2 bg-[#130F49] text-gray-50 font-light rounded-md text-lg flex flex-row items-center"
            >
              Submit
              <svg
                width="24"
                height="24"
                viewBox="0 0 24 24"
                className="text-cyan-500 ml-2"
                fill="currentColor"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M9.00967 5.12761H11.0097C12.1142 5.12761 13.468 5.89682 14.0335 6.8457L16.5089 11H21.0097C21.562 11 22.0097 11.4477 22.0097 12C22.0097 12.5523 21.562 13 21.0097 13H16.4138L13.9383 17.1543C13.3729 18.1032 12.0191 18.8724 10.9145 18.8724H8.91454L12.4138 13H5.42485L3.99036 15.4529H1.99036L4.00967 12L4.00967 11.967L2.00967 8.54712H4.00967L5.44417 11H12.5089L9.00967 5.12761Z"
                  fill="currentColor"
                />
              </svg>
            </button>




                    </form> */}









<form
          onSubmit={handleSubmit}
        //   className="rounded-lg shadow-xl flex flex-col px-8 py-8 bg-white dark:bg-blue-500"
        >
          <h1 className="text-2xl font-bold dark:text-gray-50">
            Send a message
          </h1>

          {/* <label
            htmlFor="fullname"
            className="text-gray-500 font-light mt-8 dark:text-gray-50"
          >
            Full name<span className="text-red-500 dark:text-gray-50">*</span>
          </label> */}
          <input
            type="text"
            value={fullname}
            placeholder="Enter Your Company Name" 
            onChange={(e) => {
              setFullname(e.target.value);
            }}
            name="fullname"
            // className="bg-transparent border-b py-2 pl-4 focus:outline-none focus:rounded-md focus:ring-1 ring-green-500 font-light text-gray-500"
          />
          {/* {errors?.fullname && (
            <p className="text-red-500">Fullname cannot be empty.</p>
          )} */}

          {/* <label
            htmlFor="email"
            className="text-gray-500 font-light mt-4 dark:text-gray-50"
          >
            E-mail<span className="text-red-500">*</span>
          </label> */}
          <input
            type="email"
            name="email"
            placeholder="Enter Your Email here..." 
            value={email}
            onChange={(e) => {
              setEmail(e.target.value);
            }}
            // className="bg-transparent border-b py-2 pl-4 focus:outline-none focus:rounded-md focus:ring-1 ring-green-500 font-light text-gray-500"
          />
          {/* {errors?.email && (
            <p className="text-red-500">Email cannot be empty.</p>
          )} */}

          {/* <label
            htmlFor="Phone"
            className="text-gray-500 font-light mt-4 dark:text-gray-50"
          >
            Phone<span className="text-red-500">*</span>
          </label> */}
          <input
            type="text"
            name="Phone"
            placeholder="Enter Your Phone Number" 
            value={Phone}
            onChange={(e) => {
              setPhone(e.target.value);
            }}
            // className="bg-transparent border-b py-2 pl-4 focus:outline-none focus:rounded-md focus:ring-1 ring-green-500 font-light text-gray-500"
          />
          {/* {errors?.Phone && (
            <p className="text-red-500">Phone cannot be empty.</p>
          )} */}
          {/* <label
            htmlFor="message"
            className="text-gray-500 font-light mt-4 dark:text-gray-50"
          >
            Message<span className="text-red-500">*</span>
          </label> */}
          <textarea
            name="message"
            placeholder="Any Additional Information..."
            value={message}
            onChange={(e) => {
              setMessage(e.target.value);
            }}
            // className="bg-transparent border-b py-2 pl-4 focus:outline-none focus:rounded-md focus:ring-1 ring-green-500 font-light text-gray-500"
          ></textarea>
          {/* {errors?.message && (
            <p className="text-red-500">Message body cannot be empty.</p>
          )} */}
          <div className="flex flex-row items-center justify-start">
            <button
              type="submit"
              className="px-10 mt-8 py-2 bg-[#130F49] text-gray-50 font-light rounded-md text-lg flex flex-row items-center kf-gradient-bg"
            >
              {buttonText}
              <svg
                width="24"
                height="24"
                viewBox="0 0 24 24"
                className="text-cyan-500 ml-2"
                fill="currentColor"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M9.00967 5.12761H11.0097C12.1142 5.12761 13.468 5.89682 14.0335 6.8457L16.5089 11H21.0097C21.562 11 22.0097 11.4477 22.0097 12C22.0097 12.5523 21.562 13 21.0097 13H16.4138L13.9383 17.1543C13.3729 18.1032 12.0191 18.8724 10.9145 18.8724H8.91454L12.4138 13H5.42485L3.99036 15.4529H1.99036L4.00967 12L4.00967 11.967L2.00967 8.54712H4.00967L5.44417 11H12.5089L9.00967 5.12761Z"
                  fill="currentColor"
                />
              </svg>
            </button>
          </div>
          <div className="text-left">
            {showSuccessMessage && (
              <p className="text-green-500 font-semibold text-sm my-2">
                Thankyou! Your Message has been delivered.
              </p>
            )}
            {showFailureMessage && (
              <p className="text-red-500">
                Oops! Something went wrong, please try again.
              </p>
            )}
          </div>
        </form>










                </div>










            </div>


        </div>

















    </main>

    </>
  )
}
